### ISSUE TITLE
Todo Tracker Issue: Fields to add

### ISSUE THREAD

**Issue by paulpopus** [NouanceLabs/payload-better-fields-plugin#10]
Tracking here all the planned fields to add so I don't forget:

- [ ] Alert boxes (with dynamic toggles?)
- [ ] Telephone number field based on https://www.npmjs.com/package/react-phone-number-input
- [ ] Country Select
- [ ] US States Select
- [ ] Colour Select
- [ ] Colour text input with preview and validation
- [ ] Colour picker
